sudo: false
env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.12
  - NODE_VERSION=iojs

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm config set spin false"

os:
  - osx
  - linux
script: npm run-script test-all
matrix:
  fast_finish: true

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - npm install

addons:
  code_climate:
    repo_token: a7e5fe93d63691778172958720d9fbb98e39cc1501b335fd6d3310c48ed2edca

after_script:
  - cat coverage/lcov.info | codeclimate
